/**
 * Muhur TALEBI yasam dongusu: esnaf talep acar, admin kargolar, esnaf teslim alir.
 *
 * NEDEN AYRI BIR MODUL (2026-08-25'te olculdu): "talep ac" ve "teslim aldim" IKI KEZ
 * yazilmisti — web action'inda (`src/actions/seal.ts`) ve mobil API ucunda
 * (`src/app/api/mobile/partner/seals/{request,confirm-delivery}`). Ikisi de dogrudan
 * `prisma.sealRequest`'e yaziyordu ve kopyalar ayrisimisti:
 *
 *   1. **Mobil "teslim aldim" MUHURLERI HIC ATAMIYORDU.** Web, tek transaction
 *      icinde hem talebi `DELIVERED` yapiyor hem de `Seal` satirlarini
 *      `STOCK` -> `ASSIGNED` cevirip dukkana bagliyor. Mobil yalnizca durumu
 *      yaziyordu; esnaf "teslim aldim" dedikten sonra elinde KULLANILABILIR
 *      MUHUR OLMUYORDU ve check-in "muhur bu dukkana atanmamis" diye reddediyordu.
 *   2. **Mobil talep acma adet dogrulamasi yapmiyordu** (web 1..10.000 ariyor) ve
 *      `requestedBy` / `autoGenerated` alanlarini bos birakiyordu — yani talebi
 *      kimin actigi denetim izinde kayboluyordu.
 *
 * Tek govde, iki tasiyici. Yetki (dukkan sahipligi / admin) bilerek BURADA:
 * tasiyicilarin kendi tarafinda yazdigi sey tam olarak sapan seydi.
 */
import prisma from '@/lib/db';
import logger from '@/lib/logger';
import { notificationService } from '@/services/NotificationService';

export type SealRequestActor = {
  id: string;
  role: 'PARTNER' | 'ADMIN';
};

export type SealRequestErrorCode =
  | 'FORBIDDEN'
  | 'INVALID_QUANTITY'
  | 'SHOP_NOT_FOUND'
  | 'REQUEST_NOT_FOUND'
  | 'REQUEST_NOT_SHIPPED'
  | 'REQUEST_NOT_PENDING'
  | 'TRACKING_REQUIRED'
  | 'INVALID_SERIAL_RANGE'
  | 'UNKNOWN';

export type SealRequestResult =
  | { ok: true; requestId: string }
  | { ok: false; code: SealRequestErrorCode };

export type SealDeliveryResult =
  | { ok: true; assignedCount: number }
  | { ok: false; code: SealRequestErrorCode };

/** Tek talepte istenebilecek muhur araligi. Ust sinir kazara girilen 100000'i eler. */
const MIN_QUANTITY = 1;
const MAX_QUANTITY = 10_000;

/**
 * Esnaf (veya admin) icin muhur talebi acar.
 *
 * `PARTNER` yalnizca KENDI dukkani icin acabilir; sorgu bunu `ownerId` kosuluyla
 * dogrular, ayri bir kontrol satirina birakmaz.
 */
export async function createSealRequest(
  shopId: string,
  quantity: number,
  actor: SealRequestActor,
  opts: { autoGenerated?: boolean } = {},
): Promise<SealRequestResult> {
  if (!Number.isInteger(quantity) || quantity < MIN_QUANTITY || quantity > MAX_QUANTITY) {
    return { ok: false, code: 'INVALID_QUANTITY' };
  }

  try {
    const shop = await prisma.shop.findFirst({
      where: {
        id: shopId,
        ...(actor.role === 'PARTNER' ? { ownerId: actor.id } : {}),
      },
      select: { id: true },
    });

    if (!shop) return { ok: false, code: 'SHOP_NOT_FOUND' };

    const sealRequest = await prisma.sealRequest.create({
      data: {
        shopId: shop.id,
        quantity,
        status: 'PENDING',
        /* Kim actigi denetim izinin parcasi; mobil uc bunu bos birakiyordu. */
        requestedBy: actor.id,
        autoGenerated: opts.autoGenerated ?? false,
      },
    });

    return { ok: true, requestId: sealRequest.id };
  } catch (err) {
    logger.error({ err, shopId, quantity }, 'create_seal_request_failed');
    return { ok: false, code: 'UNKNOWN' };
  }
}

/**
 * Teslim alindi: talep `DELIVERED` olur VE muhurler dukkana atanir.
 *
 * Ikisi TEK TRANSACTION icinde. Ayrilirlarsa "teslim alindi ama muhur yok" durumu
 * olusur ve check-in bloke olur — mobil ucun 2026-08-25'e kadar urettigi durum tam
 * olarak buydu, orada atama adimi hic yoktu.
 *
 * `DELIVERED` bir talebi tekrar onaylamak KASITLI olarak serbest: atama adimi
 * eksik kalmis eski kayitlari kurtarmanin tek yolu bu (yeniden calistirmak
 * guvenli, cunku yalnizca `STOCK` durumundaki muhurlere dokunuyor).
 */
export async function confirmSealDelivery(
  requestId: string,
  actor: SealRequestActor,
): Promise<SealDeliveryResult> {
  try {
    const sealRequest = await prisma.sealRequest.findUnique({
      where: { id: requestId },
      include: { shop: { select: { ownerId: true } } },
    });
    if (!sealRequest) return { ok: false, code: 'REQUEST_NOT_FOUND' };

    if (actor.role !== 'ADMIN' && sealRequest.shop.ownerId !== actor.id) {
      return { ok: false, code: 'FORBIDDEN' };
    }
    if (sealRequest.status !== 'SHIPPED' && sealRequest.status !== 'DELIVERED') {
      return { ok: false, code: 'REQUEST_NOT_SHIPPED' };
    }

    const assignedCount = await prisma.$transaction(async (tx) => {
      await tx.sealRequest.update({
        where: { id: requestId },
        data: { status: 'DELIVERED', updatedAt: new Date() },
      });

      const assignment = {
        shopId: sealRequest.shopId,
        status: 'ASSIGNED' as const,
        assignedAt: new Date(),
      };

      // Admin bir seri araligi bildirdiyse tam o araligi ata.
      if (sealRequest.serialFrom && sealRequest.serialTo) {
        const { count } = await tx.seal.updateMany({
          where: {
            serialNumber: { gte: sealRequest.serialFrom, lte: sealRequest.serialTo },
            status: 'STOCK',
          },
          data: assignment,
        });
        return count;
      }

      // Aralik yoksa stoktan sirayla `quantity` kadar muhur ayir.
      const seals = await tx.seal.findMany({
        where: { status: 'STOCK', shopId: null },
        orderBy: { serialNumber: 'asc' },
        take: sealRequest.quantity,
        select: { serialNumber: true },
      });
      if (seals.length === 0) return 0;

      const { count } = await tx.seal.updateMany({
        where: { serialNumber: { in: seals.map((s) => s.serialNumber) } },
        data: assignment,
      });
      return count;
    });

    if (assignedCount === 0) {
      /*
        Talep teslim alindi ama atanacak muhur bulunamadi (stok bitmis olabilir).
        Hata degil — ama sessiz kalirsa esnaf muhursuz kalir ve sebebi hicbir yerde
        yazmaz. Kurtarma yolu: stok yuklendikten sonra ayni talep yeniden onaylanir.
      */
      logger.warn({ requestId, shopId: sealRequest.shopId }, 'seal_delivery_no_seals_assigned');
    }

    return { ok: true, assignedCount };
  } catch (err) {
    logger.error({ err, requestId }, 'confirm_seal_delivery_failed');
    return { ok: false, code: 'UNKNOWN' };
  }
}

export type SealShipInput = {
  requestId: string;
  trackingNumber: string;
  quantity?: number;
  serialFrom?: number;
  serialTo?: number;
  adminNote?: string;
};

/**
 * Admin: talebi kargoya verir ve esnafa haber verir.
 *
 * Servise tasindi (2026-08-25) cunku `sealRequest`'e yazan son servis-disi
 * yoldu; `service-layer-writes` mandali muhur modellerini artik 0'da tutuyor.
 * Yetki (ADMIN) tasiyicida kalir — oturum/token cozumu orasinin isi.
 */
export async function shipSealRequest(input: SealShipInput): Promise<
  { ok: true } | { ok: false; code: SealRequestErrorCode }
> {
  const trackingNumber = input.trackingNumber?.trim();
  if (!trackingNumber) return { ok: false, code: 'TRACKING_REQUIRED' };

  const { serialFrom, serialTo } = input;
  if (serialFrom !== undefined && serialTo !== undefined) {
    if (!Number.isInteger(serialFrom) || !Number.isInteger(serialTo) || serialFrom > serialTo) {
      return { ok: false, code: 'INVALID_SERIAL_RANGE' };
    }
  }

  try {
    const sealRequest = await prisma.sealRequest.findUnique({
      where: { id: input.requestId },
      include: { shop: { include: { owner: { select: { email: true, phone: true } } } } },
    });
    if (!sealRequest) return { ok: false, code: 'REQUEST_NOT_FOUND' };
    if (sealRequest.status !== 'PENDING') return { ok: false, code: 'REQUEST_NOT_PENDING' };

    await prisma.sealRequest.update({
      where: { id: input.requestId },
      data: {
        status: 'SHIPPED',
        trackingNumber,
        quantity: input.quantity !== undefined ? input.quantity : undefined,
        serialFrom: serialFrom ?? null,
        serialTo: serialTo ?? null,
        adminNote: input.adminNote?.trim() || null,
        updatedAt: new Date(),
      },
    });

    await notifyShipped(sealRequest, trackingNumber, input);
    return { ok: true };
  } catch (err) {
    logger.error({ err, requestId: input.requestId }, 'ship_seal_request_failed');
    return { ok: false, code: 'UNKNOWN' };
  }
}

/**
 * Kargo bildirimi. Ayri fonksiyon: bildirimin basarisiz olmasi kargoya verme
 * islemini geri almaz — talep SHIPPED kalir, hata loglanir.
 */
async function notifyShipped(
  sealRequest: { quantity: number; shop: { name: string; owner: { email: string | null; phone: string | null } } },
  trackingNumber: string,
  input: SealShipInput,
): Promise<void> {
  const { owner, name: shopName } = sealRequest.shop;
  const serialRange =
    input.serialFrom !== undefined && input.serialTo !== undefined
      ? `${input.serialFrom} - ${input.serialTo}`
      : 'Belirtilmedi';
  const note = input.adminNote?.trim();

  const subject = 'BagajPark: Mühürleriniz Kargoya Verildi';
  const body = `Merhaba,\n\n${shopName} için talep ettiğiniz ${sealRequest.quantity} adet mühür kargoya verildi.\n\nTakip Numarası: ${trackingNumber}\nSeri Aralığı: ${serialRange}\n${note ? `\nNot: ${note}` : ''}\n\nBagajPark`;

  if (owner.email) {
    await notificationService
      .sendEmail(owner.email, subject, body)
      .catch((err) => logger.error({ err }, 'seal_shipped_email_failed'));
  }
  if (owner.phone) {
    await notificationService
      .sendSms(owner.phone, `BagajPark: Mühürleriniz kargoya verildi. Takip: ${trackingNumber}. Seri: ${serialRange}`)
      .catch((err) => logger.error({ err }, 'seal_shipped_sms_failed'));
  }
}
