import { getTranslations, setRequestLocale } from "next-intl/server";
import { auth } from "@/auth";
import { redirect } from "next/navigation";
import prisma from "@/lib/db";
import PartnerSealsClient from "@/components/partner/PartnerSealsClient";

export default async function PartnerSealsPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);
  const t = await getTranslations({ locale, namespace: "Partner" });

  const session = await auth();
  if (
    !session?.user?.id ||
    (session.user.role !== "PARTNER" && session.user.role !== "ADMIN")
  ) {
    redirect(`/${locale}/login?callbackUrl=/${locale}/partner/seals`);
  }

  const shop = await prisma.shop.findFirst({
    where: { ownerId: session.user.id },
    select: { id: true, name: true },
  });

  if (!shop) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-10">
        <p className="text-gray-500 font-bold">{t("sealsNoShop")}</p>
      </div>
    );
  }

  const [assignedCount, inUseCount, returnedCount, requests] =
    await Promise.all([
      prisma.seal.count({ where: { shopId: shop.id, status: "ASSIGNED" } }),
      prisma.seal.count({ where: { shopId: shop.id, status: "IN_USE" } }),
      prisma.seal.count({ where: { shopId: shop.id, status: "RETURNED" } }),
      prisma.sealRequest.findMany({
        where: { shopId: shop.id },
        orderBy: { createdAt: "desc" },
        take: 20,
        select: {
          id: true,
          quantity: true,
          status: true,
          trackingNumber: true,
          serialFrom: true,
          serialTo: true,
          adminNote: true,
          autoGenerated: true,
          createdAt: true,
          updatedAt: true,
        },
      }),
    ]);

  const serializedRequests = requests.map((r) => ({
    ...r,
    createdAt: r.createdAt.toISOString(),
    updatedAt: r.updatedAt.toISOString(),
  }));

  return (
    <PartnerSealsClient
      shopId={shop.id}
      shopName={shop.name}
      assignedCount={assignedCount}
      inUseCount={inUseCount}
      returnedCount={returnedCount}
      requests={serializedRequests}
    />
  );
}
