import { getTranslations, setRequestLocale } from "next-intl/server";
import prisma from "@/lib/db";
import { requirePartnerPage } from "@/lib/page-auth";
import { resolvePartnerShops } from "@/lib/partner-shop";
import PartnerSealsClient from "@/components/partner/PartnerSealsClient";

export default async function PartnerSealsPage({
  params,
  searchParams,
}: {
  params: Promise<{ locale: string }>;
  searchParams?: Promise<{ shop?: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);
  const t = await getTranslations({ locale, namespace: "Partner" });

  const actor = await requirePartnerPage(locale, "/partner/seals");

  /*
    Dukkan secimi PANELLE AYNI kuraldan (`partner-shop.ts`). Onceki hali
    `findFirst({ ownerId })` idi: siralamasiz, yani hangi dukkanin gelecegi
    veritabaninin plan secimine kalmisti. Cok dukkanli esnaf panelde
    Sultanahmet'i secip buraya gectiginde Galata'nin muhur stogunu goruyor,
    yanlis dukkan icin siparis veriyordu.
  */
  const sp = (await searchParams) ?? {};
  const { activeShop: shop } = await resolvePartnerShops(actor.id, sp.shop);

  if (!shop) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-10">
        <p className="text-gray-500 font-bold">{t("sealsNoShop")}</p>
      </div>
    );
  }

  const [assignedCount, inUseCount, returnedCount, requests] =
    await Promise.all([
      prisma.seal.count({ where: { shopId: shop.id, status: "ASSIGNED" } }),
      prisma.seal.count({ where: { shopId: shop.id, status: "IN_USE" } }),
      prisma.seal.count({ where: { shopId: shop.id, status: "RETURNED" } }),
      prisma.sealRequest.findMany({
        where: { shopId: shop.id },
        orderBy: { createdAt: "desc" },
        take: 20,
        select: {
          id: true,
          quantity: true,
          status: true,
          trackingNumber: true,
          serialFrom: true,
          serialTo: true,
          adminNote: true,
          autoGenerated: true,
          createdAt: true,
          updatedAt: true,
        },
      }),
    ]);

  const serializedRequests = requests.map((r) => ({
    ...r,
    createdAt: r.createdAt.toISOString(),
    updatedAt: r.updatedAt.toISOString(),
  }));

  return (
    <PartnerSealsClient
      shopId={shop.id}
      shopName={shop.name}
      assignedCount={assignedCount}
      inUseCount={inUseCount}
      returnedCount={returnedCount}
      requests={serializedRequests}
    />
  );
}
