import type { Prisma } from "@prisma/client";
import prisma from "@/lib/db";
import { randomUUID } from "crypto";
import { getStorage, validateImageBytes, buildObjectKey } from "@/lib/storage";
import {
  createSealRequest as createSealRequestImpl,
  confirmSealDelivery as confirmSealDeliveryImpl,
  shipSealRequest as shipSealRequestImpl,
  type SealRequestActor,
  type SealShipInput,
} from '@/services/seal/requests';

export type SealAssignmentInput = {
  sealNumber: number;
  bagIndex: number;
  bagSize: string;
};

type Tx = Omit<
  Prisma.TransactionClient,
  "$connect" | "$disconnect" | "$on" | "$transaction" | "$extends" | "$use"
>;

/**
 * Platform mühür stoku: toplu oluşturma, dükkana atama, check-in/out ile durum güncelleme.
 */
export type {
  SealShipInput,
  SealRequestActor,
  SealRequestResult,
  SealDeliveryResult,
  SealRequestErrorCode,
} from '@/services/seal/requests';

export class SealService {
  /**
   * Muhur TALEBI islemleri — govde `src/services/seal/requests.ts`'te.
   * Web action'i ve mobil uc ayni cagriyi yapar; gerekce o dosyanin basinda.
   */
  async createRequest(
    shopId: string,
    quantity: number,
    actor: SealRequestActor,
    opts?: { autoGenerated?: boolean },
  ) {
    return createSealRequestImpl(shopId, quantity, actor, opts);
  }

  async confirmDelivery(requestId: string, actor: SealRequestActor) {
    return confirmSealDeliveryImpl(requestId, actor);
  }

  /** Admin: talebi kargoya verir ve esnafa haber verir. Yetki kontrolu cagirandadir. */
  async shipRequest(input: SealShipInput) {
    return shipSealRequestImpl(input);
  }

  /**
   * Dukkan silinirken ona ATANMIS muhurleri stoga geri dondurur.
   *
   * Servise tasindi (2026-08-25): admin basvuru reddi ucu bunu ham
   * `prisma.seal.updateMany` ile yapiyordu — muhur envanteri bu servisin isi.
   */
  async releaseShopSeals(shopId: string): Promise<number> {
    const { count } = await prisma.seal.updateMany({
      where: { shopId, status: "ASSIGNED" },
      data: { status: "STOCK", shopId: null, assignedAt: null },
    });
    return count;
  }

  async bulkCreateSeals(
    fromSerial: number,
    toSerial: number
  ): Promise<{ created: number }> {
    if (!Number.isInteger(fromSerial) || !Number.isInteger(toSerial)) {
      throw new Error("invalid_range");
    }
    /*
      SERI NUMARASI POZITIF OLMAK ZORUNDA (2026-09-02'de olculdu).

      Uc kontrol de (tam sayi, sira, aralik genisligi) negatif bir araligi
      GECIRIYORDU: `bulkCreateSeals(-100, -50)` elli bir muhur, `(0, 5)` alti
      muhur uretti.

      Bunlar OLU STOK: check-in govdesi `sealNumber: z.number().int().positive()`
      istiyor, yani negatif ya da sifir numarali bir muhur hicbir zaman bir
      valize baglanamaz. Ama envanter sayimlarina giriyor
      (`getSealCounts`, dukkan stok rozeti, `seal-forecast` yeniden siparis
      esigi) -- yani sistem var olmayan bir stogu var saniyor ve gercekten
      muhur bittiginde otomatik talep acmiyor.

      Sistemin geri kalani zaten pozitif varsayiyordu; uretim tarafi bunu
      zorlamiyordu.
    */
    if (fromSerial < 1) {
      throw new Error("invalid_range");
    }
    if (fromSerial > toSerial) {
      throw new Error("invalid_range");
    }
    if (toSerial - fromSerial > 50_000) {
      throw new Error("range_too_large");
    }
    const data: { serialNumber: number; status: "STOCK" }[] = [];
    for (let n = fromSerial; n <= toSerial; n++) {
      data.push({ serialNumber: n, status: "STOCK" });
    }
    const result = await prisma.seal.createMany({
      data,
      skipDuplicates: true,
    });
    return { created: result.count };
  }

  async assignSealsToShop(
    shopId: string,
    count: number
  ): Promise<{ updated: number }> {
    if (count <= 0) {
      throw new Error("invalid_count");
    }
    const now = new Date();
    
    const seals = await prisma.seal.findMany({
      where: {
        status: "STOCK",
        shopId: null,
      },
      orderBy: { serialNumber: "asc" },
      take: count,
      select: { serialNumber: true },
    });

    if (seals.length === 0) {
      return { updated: 0 };
    }

    const result = await prisma.seal.updateMany({
      where: {
        serialNumber: { in: seals.map((s) => s.serialNumber) },
      },
      data: {
        shopId,
        status: "ASSIGNED",
        assignedAt: now,
      },
    });
    return { updated: result.count };
  }

  async getSealCounts() {
    const grouped = await prisma.seal.groupBy({
      by: ["status"],
      _count: { serialNumber: true },
    });
    const map: Record<string, number> = {};
    for (const g of grouped) {
      map[g.status] = g._count.serialNumber;
    }
    return map;
  }

  /**
   * Check-in içinde: hatalı mühürleri FAULTY yap, atananları IN_USE + BookingSeal kaydı.
   */
  /**
   * Mühür kanıt fotoğrafını depolamaya yazar ve adresini döndürür.
   *
   * TRANSACTION'IN DIŞINDA çağrılmalı: ağ işi bir veritabanı işleminin içinde
   * yapılamaz — yavaş bir yükleme, kilitleri tutan bir transaction demektir.
   * Bu yüzden sıra şu: fotoğrafı yaz → adresi al → transaction'ı aç.
   *
   * Fotoğrafın kendisi ZORUNLU DEĞİL. Zorunlu kılmak, kamerası çalışmayan ya
   * da izin vermeyen bir esnafın valizi HİÇ teslim alamaması demek olurdu;
   * `requireSealsOnCheckIn` ayarının lansmanda `false` bırakılma gerekçesiyle
   * aynı (P1-23): kanıt toplamak iyidir, işi durdurmak değil.
   */
  async uploadSealPhoto(params: {
    bookingId: string;
    bytes: Uint8Array;
  }): Promise<
    | { ok: true; url: string }
    | { ok: false; reason: "empty" | "too_large" | "unsupported_type" }
  > {
    const validation = validateImageBytes(params.bytes);
    if (!validation.ok) return { ok: false, reason: validation.reason };

    const storage = getStorage();
    const key = buildObjectKey({
      prefix: "seals",
      ownerId: params.bookingId,
      uniqueId: randomUUID(),
      extension: validation.extension,
    });
    const { url } = await storage.put({
      key,
      body: params.bytes,
      contentType: validation.contentType,
    });
    return { ok: true, url };
  }

  async applyCheckInWithinTx(
    tx: Tx,
    params: {
      shopId: string;
      bookingId: string;
      assignments: SealAssignmentInput[];
      faultySealNumbers: number[];
      /**
       * Mühürlenmiş valizin kanıt fotoğrafı.
       *
       * ARTIK DOLUYOR (2026-09-01). 2026-09-01 öncesinde tek çağıran
       * (`booking/check-in.ts`) buraya sabit `null` geçiyordu ve
       * `CheckInDialog` içinde kamera alanı yoktu — yani ürün üç yerde
       * "teslimde mühür ve fotoğraf" vaat ederken `BookingSeal.photoUrl`
       * hiçbir zaman dolmuyordu. Tek engel bir görsel depolama kararıydı;
       * karar S3 olarak verildi (`src/lib/storage/`).
       *
       * DEĞER SUNUCUDAN GELİR. `checkInAction` baytları doğrulayıp depolamaya
       * yazar ve dönen adresi buraya koyar; istemcinin gönderdiği bir adres
       * asla buraya ulaşmaz. Aksi hâlde esnaf uyuşmazlıkta "kanıt" diye
       * kendi seçtiği bir görseli gösterebilirdi.
       *
       * Fotoğraf ZORUNLU DEĞİL: kamerası çalışmayan bir esnafın valizi hiç
       * teslim alamaması, kanıt toplayamamaktan kötüdür.
       */
      sealPhotoUrl: string | null;
    }
  ): Promise<void> {
    const { shopId, bookingId, assignments, faultySealNumbers, sealPhotoUrl } =
      params;

    const assignmentNums = new Set(assignments.map((a) => a.sealNumber));
    if (assignmentNums.size !== assignments.length) {
      throw new Error("duplicate_seal_in_assignments");
    }
    for (const sn of faultySealNumbers) {
      if (assignmentNums.has(sn)) {
        throw new Error("faulty_overlaps_assignment");
      }
    }

    if (faultySealNumbers.length > 0) {
      const faultySeals = await tx.seal.findMany({
        where: { serialNumber: { in: faultySealNumbers } },
      });
      for (const seal of faultySeals) {
        if (seal.shopId !== shopId || seal.status !== "ASSIGNED") {
          throw new Error(`SEAL_FAULTY_INVALID:${seal.serialNumber}`);
        }
      }
      if (faultySeals.length !== faultySealNumbers.length) {
        const found = new Set(faultySeals.map((s) => s.serialNumber));
        const missing = faultySealNumbers.find((sn) => !found.has(sn));
        throw new Error(`SEAL_FAULTY_INVALID:${missing}`);
      }
      await tx.seal.updateMany({
        where: { serialNumber: { in: faultySealNumbers } },
        data: { status: "FAULTY" },
      });
    }

    if (assignments.length > 0) {
      const assignmentNumsArr = assignments.map((a) => a.sealNumber);
      const existingSeals = await tx.seal.findMany({
        where: { serialNumber: { in: assignmentNumsArr } },
      });
      const sealMap = new Map(existingSeals.map((s) => [s.serialNumber, s]));
      for (const a of assignments) {
        const seal = sealMap.get(a.sealNumber);
        if (!seal || seal.shopId !== shopId) {
          throw new Error(`SEAL_INVALID:${a.sealNumber}`);
        }
        if (seal.status !== "ASSIGNED") {
          throw new Error(`SEAL_NOT_ASSIGNED:${a.sealNumber}`);
        }
      }

      /*
        MUHRU ATOMIK OLARAK KAPAR (2026-09-02'de gercek veritabaninda olculdu).

        Yukaridaki dogrulama okuma-sonra-yazma: uc es zamanli check-in ayni
        muhrü ASSIGNED gorur, ucu de kontrolu gecer ve ucu de kayit yazardi.
        Olcum -- ayni muhurle dort es zamanli check-in:

            check-in basarili: 3
            ayni muhre bagli kayit: 3
            muhur durumu: IN_USE

        Fiziksel muhur TEK bir valizde. Uc rezervasyonun kaydinda ayni numara
        gorunurse teslimde hangisinin dogru oldugu bilinemez -- urunun guven
        mekanizmasi tam da bu numaranin tekligine dayaniyor.

        `status: "ASSIGNED"` KOSULU eklendi: guncelleme yalnizca muhur HALA
        stokta ise geciyor ve etkilenen satir sayisi bekleneni tutmuyorsa
        baskasi kapmis demektir. Ayni kalip kupon kotasinda zaten var ve
        calisiyor (yirmi es zamanli talepten tam bes hak veriyor, olculdu).
      */
      const kapilan = await tx.seal.updateMany({
        where: { serialNumber: { in: assignmentNumsArr }, status: "ASSIGNED" },
        data: { status: "IN_USE" },
      });
      if (kapilan.count !== assignmentNumsArr.length) {
        /*
          Hangi muhrun kapildigini burada aramiyoruz: islem geri alinacak ve
          cagiran zaten "gecersiz muhur" cevabini veriyor. Onemli olan, bu
          check-in'in KAYIT YAZMAMASI.
        */
        throw new Error(`SEAL_NOT_ASSIGNED:${assignmentNumsArr.join(",")}`);
      }

      await tx.bookingSeal.createMany({
        data: assignments.map((a, i) => ({
          bookingId,
          sealNumber: a.sealNumber,
          bagIndex: a.bagIndex,
          bagSize: a.bagSize,
          photoUrl: i === 0 ? sealPhotoUrl : null,
        })),
      });
    }
  }

  /**
   * Dükkanın stoğundaki (ASSIGNED) en küçük seri numaralı N mühürü getirir.
   */
  async getNextAvailableSeals(shopId: string, count: number) {
    return await prisma.seal.findMany({
      where: {
        shopId,
        status: "ASSIGNED",
      },
      orderBy: { serialNumber: "asc" },
      take: count,
    });
  }

  /**
   * Bir mühürü FAULTY olarak işaretler ve kullanımdan çıkarır.
   */
  /**
   * Muhuru ARIZALI isaretler.
   *
   * `actor` ZORUNLU (2026-08-31'de eklendi). Onceden yalnizca `shopId`
   * aliyordu ve "muhur bu dukkanin mi" sorusuna bakiyordu; "CAGIRAN bu
   * dukkanin sahibi mi" sorusunu HIC sormuyordu. `shopId` istemciden geliyor,
   * yani bir esnaf baska bir dukkanin kimligini gecirip O dukkanin muhurlerini
   * arizali isaretleyebiliyordu.
   *
   * Etkisi envanterle sinirli degil: FAULTY bir muhur check-in'de reddediliyor
   * (bu dosyada, `applyCheckInWithinTx`), yani hedef dukkanin teslim alma akisi
   * duruyordu. Seri numaralari ardisik tam sayi, dukkan kimlikleri de herkese
   * acik sayfalarda -- ikisini de taramak gerekmiyor, okunuyor.
   *
   * Mobil uc (`/api/mobile/partner/seals/report-faulty`) bu saldiriyi 2026-08-25'te
   * ZATEN kapatmisti: dukkani cagirandan turetiyor, istemciden almiyor. Web
   * action'i (`reportFaultySealAction`) kapatmamisti -- ayni kuralin iki
   * tasiyicida ayri yazilmasinin bilinen sonucu. Kural artik SERVISTE, yani
   * ucuncu bir tasiyici eklendiginde de gecerli.
   */
  async markSealAsFaulty(
    serialNumber: number,
    shopId: string,
    actor: { id: string; role: string },
  ): Promise<void> {
    if (actor.role !== "ADMIN") {
      const owned = await prisma.shop.findFirst({
        where: { id: shopId, ownerId: actor.id },
        select: { id: true },
      });
      if (!owned) {
        throw new Error("shop_not_owned_by_actor");
      }
    }

    const seal = await prisma.seal.findUnique({
      where: { serialNumber },
    });

    if (!seal || seal.shopId !== shopId) {
      throw new Error("seal_not_owned_by_shop");
    }

    if (seal.status === "IN_USE" || seal.status === "RETURNED") {
       throw new Error("seal_already_processed");
    }

    await prisma.seal.update({
      where: { serialNumber },
      data: { status: "FAULTY" },
    });
  }

  /**
   * Check-out: BookingSeal kayıtlarındaki mühürleri RETURNED yap.
   */
  async applyCheckOutReturnSealsWithinTx(tx: Tx, bookingId: string): Promise<void> {
    const rows = await tx.bookingSeal.findMany({
      where: { bookingId },
      select: { sealNumber: true },
    });
    const serialNumbers = rows.map((r) => r.sealNumber);
    if (serialNumbers.length > 0) {
      await tx.seal.updateMany({
        where: { serialNumber: { in: serialNumbers } },
        data: { status: "RETURNED" },
      });
    }
  }

  /**
   * Önümüzdeki `daysAhead` günde bu dükkan için kaç mühüre ihtiyaç var?
   * APPROVED + PAID + CHECKED_IN durumundaki rezervasyonların valiz sayılarını toplar.
   */
  async predictSealDemand(shopId: string, daysAhead: number): Promise<number> {
    const now = new Date();
    const future = new Date(now.getTime() + daysAhead * 24 * 60 * 60 * 1000);
    const bookings = await prisma.booking.findMany({
      where: {
        shopId,
        status: { in: ["APPROVED", "PAID", "CHECKED_IN"] },
        checkInTime: { gte: now, lte: future },
      },
      select: { bagCountS: true, bagCountM: true, bagCountXl: true },
    });
    return bookings.reduce(
      (sum, b) => sum + b.bagCountS + b.bagCountM + b.bagCountXl,
      0
    );
  }

  /**
   * Dükkanın RETURNED mühürlerini ASSIGNED'a geri alır (iade sonrası tekrar kullanım).
   * count verilmezse tüm RETURNED mühürleri geri alır.
   * Returns: recycled count
   */
  async recycleReturnedSeals(shopId: string, count?: number): Promise<number> {
    return await prisma.$transaction(async (tx) => {
      const where: Prisma.SealWhereInput = {
        shopId,
        status: "RETURNED",
      };
      
      if (count !== undefined) {
        // Fetch IDs within transaction
        const seals = await tx.seal.findMany({
          where,
          select: { serialNumber: true },
          take: count,
          orderBy: { serialNumber: "asc" },
        });
        
        if (seals.length === 0) return 0;
        
        const result = await tx.seal.updateMany({
          where: { serialNumber: { in: seals.map((s) => s.serialNumber) } },
          data: { status: "ASSIGNED" },
        });
        return result.count;
      }
      
      const result = await tx.seal.updateMany({ where, data: { status: "ASSIGNED" } });
      return result.count;
    });
  }

  /**
   * Dükkanın mühür hazırlık durumunu döndürür.
   */
  async checkShopSealReadiness(
    shopId: string,
    daysAhead: number = 7
  ): Promise<{
    assignedCount: number;
    returnedCount: number;
    predictedDemand: number;
    shortfall: number;
    ok: boolean;
  }> {
    const [assignedCount, returnedCount, predictedDemand] = await Promise.all([
      prisma.seal.count({ where: { shopId, status: "ASSIGNED" } }),
      prisma.seal.count({ where: { shopId, status: "RETURNED" } }),
      this.predictSealDemand(shopId, daysAhead),
    ]);
    const shortfall = Math.max(0, predictedDemand - assignedCount);
    return {
      assignedCount,
      returnedCount,
      predictedDemand,
      shortfall,
      ok: shortfall === 0,
    };
  }

  /**
   * Aktif atamaları (ASSIGNED) dükkan bazlı ve ardışık aralıklar halinde getirir.
   */
  async getAssignedSealBatches() {
    const seals = await prisma.seal.findMany({
      where: { status: "ASSIGNED", shopId: { not: null } },
      include: { shop: { select: { name: true } } },
      orderBy: { serialNumber: "asc" },
    });

    if (seals.length === 0) return [];

    const batches: {
      shopId: string;
      shopName: string;
      fromSerial: number;
      toSerial: number;
      count: number;
    }[] = [];

    let currentBatch = {
      shopId: seals[0].shopId!,
      shopName: seals[0].shop?.name || "Unknown",
      fromSerial: seals[0].serialNumber,
      toSerial: seals[0].serialNumber,
      count: 1,
    };

    for (let i = 1; i < seals.length; i++) {
      const s = seals[i];
      const isContiguous = s.serialNumber === currentBatch.toSerial + 1;
      const isSameShop = s.shopId === currentBatch.shopId;

      if (isContiguous && isSameShop) {
        currentBatch.toSerial = s.serialNumber;
        currentBatch.count++;
      } else {
        batches.push(currentBatch);
        currentBatch = {
          shopId: s.shopId!,
          shopName: s.shop?.name || "Unknown",
          fromSerial: s.serialNumber,
          toSerial: s.serialNumber,
          count: 1,
        };
      }
    }
    batches.push(currentBatch);

    // En son verilen batçları en üstte göstermek için bitiş seri nosuna göre ters sıralayalım
    return batches.sort((a, b) => b.toSerial - a.toSerial);
  }
}

export const sealService = new SealService();
