include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated_plugin_registrant.dart"
  errors:
    todo: ignore
    missing_required_param: error
    missing_return: error
    unused_import: error
    unused_local_variable: error
    dead_code: error

linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_escaping_inner_quotes
    - avoid_redundant_argument_values
    - avoid_unused_constructor_parameters
    - cascade_invocations
    - directives_ordering
    - omit_local_variable_types
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_locals
    - prefer_interpolation_to_compose_strings
    - prefer_single_quotes
    - require_trailing_commas
    - sort_child_properties_last
    - sort_unnamed_constructors_first
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_lambdas
    - use_decorated_box
    - use_is_even_rather_than_modulo
