-- Migration: seal_logistics
-- Adds logistics fields to SealRequest and reorder config to Shop

-- SealRequest: new logistics columns
ALTER TABLE "SealRequest" ADD COLUMN "trackingNumber" TEXT;
ALTER TABLE "SealRequest" ADD COLUMN "adminNote" TEXT;
ALTER TABLE "SealRequest" ADD COLUMN "serialFrom" INTEGER;
ALTER TABLE "SealRequest" ADD COLUMN "serialTo" INTEGER;
ALTER TABLE "SealRequest" ADD COLUMN "autoGenerated" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "SealRequest" ADD COLUMN "requestedBy" TEXT;

-- Shop: seal reorder config
ALTER TABLE "Shop" ADD COLUMN "sealReorderPoint" INTEGER NOT NULL DEFAULT 15;
ALTER TABLE "Shop" ADD COLUMN "sealLeadTimeDays" INTEGER NOT NULL DEFAULT 3;
