"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Link } from "@/i18n/routing";
import {
  ArrowLeft,
  Shield,
  Package,
  RefreshCw,
  CheckCircle2,
  Clock,
  Truck,
  AlertTriangle,
  Plus,
} from "lucide-react";
import {
  requestSealsAction,
  confirmSealDeliveryAction,
  recycleReturnedSealsAction,
} from "@/actions/seal";

interface SealRequestRow {
  id: string;
  quantity: number;
  status: string;
  trackingNumber: string | null;
  serialFrom: number | null;
  serialTo: number | null;
  adminNote: string | null;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

interface Props {
  shopId: string;
  shopName: string;
  assignedCount: number;
  inUseCount: number;
  returnedCount: number;
  requests: SealRequestRow[];
}

function StatusBadge({ status }: { status: string }) {
  if (status === "PENDING")
    return (
      <span className="inline-flex items-center gap-1 text-[10px] font-black uppercase tracking-widest text-orange-600 bg-orange-50 px-2 py-1 rounded-lg">
        <Clock size={10} /> Bekliyor
      </span>
    );
  if (status === "SHIPPED")
    return (
      <span className="inline-flex items-center gap-1 text-[10px] font-black uppercase tracking-widest text-blue-600 bg-blue-50 px-2 py-1 rounded-lg">
        <Truck size={10} /> Kargoda
      </span>
    );
  return (
    <span className="inline-flex items-center gap-1 text-[10px] font-black uppercase tracking-widest text-green-600 bg-green-50 px-2 py-1 rounded-lg">
      <CheckCircle2 size={10} /> Teslim Edildi
    </span>
  );
}

export default function PartnerSealsClient({
  shopId,
  shopName,
  assignedCount,
  inUseCount,
  returnedCount,
  requests,
}: Props) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [requestQty, setRequestQty] = useState("20");
  const [showRequestForm, setShowRequestForm] = useState(false);
  const [feedback, setFeedback] = useState<{ msg: string; ok: boolean } | null>(null);

  const totalUsable = assignedCount + returnedCount;
  const isLow = assignedCount < 10;

  const showFeedback = (msg: string, ok: boolean) => {
    setFeedback({ msg, ok });
    setTimeout(() => setFeedback(null), 4000);
  };

  const handleRequestSeals = () => {
    const qty = parseInt(requestQty, 10);
    if (!qty || qty < 1) return;
    startTransition(async () => {
      const res = await requestSealsAction(qty);
      if (res.success) {
        showFeedback(`${qty} adet mühür talebi oluşturuldu. Admin onayını bekleyiniz.`, true);
        setShowRequestForm(false);
        router.refresh();
      } else {
        showFeedback(res.error ?? "Bir hata oluştu.", false);
      }
    });
  };

  const handleConfirmDelivery = (requestId: string) => {
    startTransition(async () => {
      const res = await confirmSealDeliveryAction(requestId);
      if (res.success) {
        showFeedback("Teslimat onaylandı! Mühürler stoğunuza eklendi.", true);
        router.refresh();
      } else {
        showFeedback(res.error ?? "Bir hata oluştu.", false);
      }
    });
  };

  const handleRecycle = () => {
    startTransition(async () => {
      const res = await recycleReturnedSealsAction(shopId);
      if (res.success) {
        showFeedback(`${res.recycled} iade mühür tekrar kullanıma alındı.`, true);
        router.refresh();
      } else {
        showFeedback(res.error ?? "Bir hata oluştu.", false);
      }
    });
  };

  return (
    <div className="min-h-screen bg-gray-50 pb-24">
      <header className="bg-white border-b border-gray-100 px-6 py-4 flex items-center gap-3 sticky top-0 z-10">
        <Link href="/partner" className="p-2 hover:bg-gray-100 rounded-full transition-colors">
          <ArrowLeft size={20} />
        </Link>
        <div>
          <h1 className="text-lg font-black text-gray-900">Mühür Yönetimi</h1>
          <p className="text-xs text-gray-400">{shopName}</p>
        </div>
      </header>

      <main className="max-w-lg mx-auto p-4 space-y-4">
        {/* Feedback */}
        {feedback && (
          <div
            className={`rounded-2xl px-4 py-3 text-sm font-semibold ${
              feedback.ok
                ? "bg-green-50 text-green-700 border border-green-100"
                : "bg-red-50 text-red-700 border border-red-100"
            }`}
          >
            {feedback.msg}
          </div>
        )}

        {/* Low stock warning */}
        {isLow && (
          <div className="bg-amber-50 border border-amber-200 rounded-2xl px-4 py-3 flex items-center gap-3">
            <AlertTriangle size={18} className="text-amber-500 shrink-0" />
            <p className="text-sm text-amber-800 font-semibold">
              Düşük stok! Yalnızca <strong>{assignedCount}</strong> kullanılabilir mühürünüz var. Lütfen talep açın.
            </p>
          </div>
        )}

        {/* Stock cards */}
        <div className="grid grid-cols-3 gap-3">
          <div className="bg-white rounded-2xl border border-gray-100 p-4 text-center">
            <Shield size={18} className="text-green-500 mx-auto mb-1" />
            <p className="text-2xl font-black text-gray-900">{assignedCount}</p>
            <p className="text-xs text-gray-400 mt-0.5">Hazır</p>
          </div>
          <div className="bg-white rounded-2xl border border-gray-100 p-4 text-center">
            <Package size={18} className="text-orange-400 mx-auto mb-1" />
            <p className="text-2xl font-black text-gray-900">{inUseCount}</p>
            <p className="text-xs text-gray-400 mt-0.5">Kullanımda</p>
          </div>
          <div className="bg-white rounded-2xl border border-gray-100 p-4 text-center">
            <RefreshCw size={18} className="text-blue-400 mx-auto mb-1" />
            <p className="text-2xl font-black text-gray-900">{returnedCount}</p>
            <p className="text-xs text-gray-400 mt-0.5">İade</p>
          </div>
        </div>

        {/* Recycle returned seals */}
        {returnedCount > 0 && (
          <button
            onClick={handleRecycle}
            disabled={isPending}
            className="w-full bg-blue-50 hover:bg-blue-100 text-blue-700 font-bold text-sm py-3 rounded-2xl border border-blue-100 transition-colors flex items-center justify-center gap-2 disabled:opacity-60"
          >
            <RefreshCw size={16} />
            {returnedCount} İade Mühürü Tekrar Kullanıma Al
          </button>
        )}

        {/* Request new seals */}
        <div className="bg-white rounded-2xl border border-gray-100 p-5">
          <div className="flex items-center justify-between mb-3">
            <h2 className="font-bold text-gray-900 text-sm">Mühür Talebi</h2>
            {!showRequestForm && (
              <button
                onClick={() => setShowRequestForm(true)}
                className="flex items-center gap-1.5 text-xs font-bold text-orange-600 hover:text-orange-700"
              >
                <Plus size={14} />
                Yeni Talep
              </button>
            )}
          </div>

          {showRequestForm && (
            <div className="flex gap-2">
              <input
                type="number"
                value={requestQty}
                onChange={(e) => setRequestQty(e.target.value)}
                min={1}
                max={500}
                className="flex-1 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-orange-400"
                placeholder="Adet"
              />
              <button
                onClick={handleRequestSeals}
                disabled={isPending}
                className="bg-orange-500 hover:bg-orange-600 text-white font-bold text-sm px-4 py-2 rounded-xl transition-colors disabled:opacity-60"
              >
                {isPending ? "…" : "Talep Et"}
              </button>
              <button
                onClick={() => setShowRequestForm(false)}
                className="text-gray-400 hover:text-gray-600 px-2 py-2 rounded-xl"
              >
                ✕
              </button>
            </div>
          )}

          {!showRequestForm && (
            <p className="text-xs text-gray-400">
              Mühür stoğunuz azaldığında buradan talep açabilirsiniz. Sistem {totalUsable < 15 ? "otomatik talep açmış olabilir — " : ""}admin onayından sonra kargoya verilir.
            </p>
          )}
        </div>

        {/* Request history */}
        {requests.length > 0 && (
          <div className="bg-white rounded-2xl border border-gray-100 overflow-hidden">
            <div className="px-5 py-3 border-b border-gray-50">
              <h2 className="font-bold text-gray-900 text-sm">Talep Geçmişi</h2>
            </div>
            <div className="divide-y divide-gray-50">
              {requests.map((req) => (
                <div key={req.id} className="px-5 py-4">
                  <div className="flex items-start justify-between gap-3 mb-2">
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-bold text-gray-900">
                          {req.quantity} adet
                        </span>
                        {req.autoGenerated && (
                          <span className="text-[9px] font-black uppercase tracking-widest text-purple-600 bg-purple-50 px-1.5 py-0.5 rounded">
                            Otomatik
                          </span>
                        )}
                      </div>
                      <p className="text-xs text-gray-400 mt-0.5">
                        {new Date(req.createdAt).toLocaleDateString("tr-TR")}
                      </p>
                    </div>
                    <StatusBadge status={req.status} />
                  </div>

                  {req.status === "SHIPPED" && req.trackingNumber && (
                    <div className="bg-blue-50 rounded-xl px-3 py-2 mt-2 text-xs text-blue-700">
                      <p className="font-bold">Takip No: {req.trackingNumber}</p>
                      {req.serialFrom && req.serialTo && (
                        <p className="mt-0.5">
                          Seri: {req.serialFrom} – {req.serialTo}
                        </p>
                      )}
                      {req.adminNote && (
                        <p className="mt-0.5 text-blue-500">{req.adminNote}</p>
                      )}
                    </div>
                  )}

                  {req.status === "DELIVERED" && req.serialFrom && req.serialTo && (
                    <div className="bg-green-50 rounded-xl px-3 py-2 mt-2 text-xs text-green-700">
                      Seri: {req.serialFrom} – {req.serialTo}
                    </div>
                  )}

                  {req.status === "SHIPPED" && (
                    <button
                      onClick={() => handleConfirmDelivery(req.id)}
                      disabled={isPending}
                      className="mt-3 w-full bg-green-500 hover:bg-green-600 text-white font-bold text-xs py-2.5 rounded-xl transition-colors disabled:opacity-60 flex items-center justify-center gap-1.5"
                    >
                      <CheckCircle2 size={14} />
                      Teslim Aldım — Stoğa Ekle
                    </button>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

        {requests.length === 0 && (
          <p className="text-center text-sm text-gray-400 py-6">
            Henüz mühür talebiniz yok.
          </p>
        )}
      </main>
    </div>
  );
}
