import { NextRequest, NextResponse } from "next/server";
import { authorizeCron } from "@/lib/internal-api-guard";
import prisma from "@/lib/db";
import { withJobRun } from "@/lib/jobs/run-ledger";
import { notificationService } from "@/services/NotificationService";
import { parseAdminGsmNumbers } from "@/lib/netgsm";
import logger from "@/lib/logger";
import { sealService } from "@/services/SealService";

async function runSealForecast(req: NextRequest): Promise<NextResponse> {
  /*
    ORTAK KAPIYA GECILDI (2026-08-31). Bu dosya `CRON_SECRET` karsilastirmasini
    kendi icinde yaziyordu ve `bearer === secret` kullaniyordu -- yani sabit
    ZAMANLI olmayan bir karsilastirma. `authorizeCron` ayni isi
    `crypto.timingSafeEqual` ile yapiyor ve zaten UC ucta kullaniliyordu; bu dosya
    (ve iki kardesi) kopyada kalmisti. Kopya olmasi, `internal-api-guard.ts`in var
    olma gerekcesinin tam olarak gerceklestigi yer: bir uc duzeltilirken digerleri
    unutuluyor.
  */
  const denial = authorizeCron(req);
  if (denial === "not_configured") {
    return NextResponse.json(
      { ok: false, error: "CRON_SECRET not configured" },
      { status: 503 },
    );
  }
  if (denial) {
    return NextResponse.json({ ok: false, error: "Unauthorized" }, { status: 401 });
  }

  // Defter kaydi: HTTP 200 donmek yetmiyor, is CALISTIGINI JobRun'a yazmali.
  // Yoksa /api/health/jobs bu isi hic gormez ve enforced=true yapildiginda
  // sonsuza dek "gecikmis" gorunur (2026-08-29: sekiz isten dordu boyleydi).
  const outcome = await withJobRun("seal-forecast", async () => {
    const shops = await prisma.shop.findMany({
      where: { isActive: true },
      select: {
        id: true,
        name: true,
        sealReorderPoint: true,
        owner: { select: { email: true, phone: true } },
      },
    });

    if (shops.length === 0) {
      // Aktif dukkan yoksa is BASARIYLA calismistir -- deftere de oyle gecer.
      // "Yapacak is yoktu" ile "calismadi" ayni sey degil.
      return { ok: true as const, detail: { processed: 0, alerts: [], autoRequests: 0 } };
    }

    const shopIds = shops.map(s => s.id);

    const [assignedCounts, pendingRequests, upcomingBookings] = await Promise.all([
      prisma.seal.groupBy({
        by: ['shopId'],
        where: { shopId: { in: shopIds }, status: "ASSIGNED" },
        _count: true,
      }),
      prisma.sealRequest.groupBy({
        by: ['shopId'],
        where: { shopId: { in: shopIds }, status: "PENDING" },
        _count: true,
      }),
      prisma.booking.findMany({
        where: {
          shopId: { in: shopIds },
          status: { in: ["APPROVED", "PAID", "CHECKED_IN"] },
          checkInTime: { gte: new Date(), lte: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000) },
        },
        select: { shopId: true, bagCountS: true, bagCountM: true, bagCountXl: true },
      }),
    ]);

    const assignedMap = new Map(assignedCounts.map(g => [g.shopId, g._count]));
    const pendingMap = new Map(pendingRequests.map(g => [g.shopId, g._count]));
    const demandMap = new Map<string, number>();
    for (const b of upcomingBookings) {
      demandMap.set(b.shopId, (demandMap.get(b.shopId) ?? 0) + b.bagCountS + b.bagCountM + b.bagCountXl);
    }

    const alerts: string[] = [];
    let autoRequests = 0;
    let processed = 0;
    const detailedAlerts: string[] = [];

    for (const shop of shops) {
      try {
        const reorderPoint = shop.sealReorderPoint ?? 15;
        const assignedCount = assignedMap.get(shop.id) ?? 0;
        const existingPending = pendingMap.get(shop.id) ?? 0;
        const predictedDemand = demandMap.get(shop.id) ?? 0;

        processed++;

        const shouldAutoRequest =
          assignedCount < reorderPoint && existingPending === 0;

        if (shouldAutoRequest) {
          const newQuantity = reorderPoint * 2;
          /*
            Otomatik talep de esnafın açtığı taleple AYNI yoldan geçer
            (`SealService.createRequest`): adet doğrulaması, alan varsayılanları ve
            denetim izi tek yerde kalsın. `requestedBy: "system"` aktör kimliğidir.
          */
          const created = await sealService.createRequest(
            shop.id,
            newQuantity,
            { id: "system", role: "ADMIN" },
            { autoGenerated: true },
          );
          if (!created.ok) {
            logger.error(
              { shopId: shop.id, code: created.code },
              "seal_forecast_auto_request_failed",
            );
            continue;
          }
          autoRequests++;

          const alertMsg = `Dükkan: ${shop.name} | ASSIGNED: ${assignedCount} < reorder ${reorderPoint} | Talep: ${newQuantity} adet`;
          alerts.push(alertMsg);
          detailedAlerts.push(
            `- ${shop.name}: ${assignedCount}/${reorderPoint} stok. ${newQuantity} mühür talep edildi. (7 günlük tahmin: ${predictedDemand})`
          );

          logger.info(
            { shopId: shop.id, shopName: shop.name, assignedCount, reorderPoint },
            "seal_forecast_auto_request_created"
          );
        }
      } catch (shopErr) {
        logger.error({ err: shopErr, shopId: shop.id }, "seal_forecast_shop_error");
      }
    }

    // BUG-16: Send summary notification instead of triggering per shop
    if (autoRequests > 0) {
      const adminEmail = process.env.ADMIN_EMAIL?.trim();
      const summaryText = detailedAlerts.join("\n");

      if (adminEmail) {
        const emailSubject = `BagajPark [Admin]: ${autoRequests} Dükkan için Otomatik Mühür Talebi`;
        const emailBody = `Aşağıdaki dükkanlar için düşük mühür stoku nedeniyle otomatik talepler oluşturuldu:\n\n${summaryText}\n\nAdmin panelinden onaylayın: https://bagajpark.com/tr/admin/seals`;
        await notificationService.sendEmail(adminEmail, emailSubject, emailBody).catch(e => logger.error({ err: e }, "seal_forecast_email_summary_failed"));
      }

      for (const adminPhone of parseAdminGsmNumbers()) {
        const sms = `BagajPark: ${autoRequests} dükkan için mühür talebi açıldı. Detaylar email ile gönderildi.`;
        await notificationService.sendSms(adminPhone, sms).catch(e => logger.error({ err: e }, "seal_forecast_sms_summary_failed"));
      }
    }

    logger.info({ processed, alerts: alerts.length, autoRequests }, "seal_forecast_complete");

    return { ok: true as const, detail: { processed, alerts, autoRequests } };
  });

  if (!outcome.ok) {
    logger.error({ error: outcome.error }, "seal_forecast_failed");
    return NextResponse.json({ ok: false, error: outcome.error }, { status: 500 });
  }
  return NextResponse.json({ ok: true, ...outcome.detail });
}

/**
 * Daily cron: mühür stok tahmini ve otomatik talep oluşturma.
 * Auth: Authorization: Bearer <CRON_SECRET>
 */
export async function GET(req: NextRequest) {
  return runSealForecast(req);
}

export async function POST(req: NextRequest) {
  return runSealForecast(req);
}
