import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/db";
import { sealService } from "@/services/SealService";
import { notificationService } from "@/services/NotificationService";
import { parseAdminGsmNumbers } from "@/lib/netgsm";
import logger from "@/lib/logger";

function authorize(req: NextRequest): boolean {
  const secret = process.env.CRON_SECRET?.trim();
  if (!secret) return false;
  const auth = req.headers.get("authorization");
  const bearer = auth?.startsWith("Bearer ") ? auth.slice(7).trim() : null;
  const headerSecret = req.headers.get("x-cron-secret");
  return bearer === secret || headerSecret === secret;
}

async function runSealForecast(req: NextRequest): Promise<NextResponse> {
  if (!process.env.CRON_SECRET?.trim()) {
    logger.warn({}, "seal_forecast_disabled_no_cron_secret");
    return NextResponse.json(
      { ok: false, error: "CRON_SECRET not configured" },
      { status: 503 }
    );
  }
  if (!authorize(req)) {
    return NextResponse.json({ ok: false, error: "Unauthorized" }, { status: 401 });
  }

  try {
    const shops = await prisma.shop.findMany({
      where: { isActive: true },
      select: {
        id: true,
        name: true,
        sealReorderPoint: true,
        owner: { select: { email: true, phone: true } },
      },
    });

    const alerts: string[] = [];
    let autoRequests = 0;
    let processed = 0;
    let detailedAlerts: string[] = [];

    for (const shop of shops) {
      try {
        const reorderPoint = shop.sealReorderPoint ?? 15;

        const [assignedCount, predictedDemand, existingPending] =
          await Promise.all([
            prisma.seal.count({ where: { shopId: shop.id, status: "ASSIGNED" } }),
            sealService.predictSealDemand(shop.id, 7),
            prisma.sealRequest.count({
              where: { shopId: shop.id, status: "PENDING" },
            }),
          ]);

        processed++;

        const shouldAutoRequest =
          assignedCount < reorderPoint && existingPending === 0;

        if (shouldAutoRequest) {
          const newQuantity = reorderPoint * 2;
          await prisma.sealRequest.create({
            data: {
              shopId: shop.id,
              quantity: newQuantity,
              status: "PENDING",
              autoGenerated: true,
              requestedBy: "system",
            },
          });
          autoRequests++;

          const alertMsg = `Dükkan: ${shop.name} | ASSIGNED: ${assignedCount} < reorder ${reorderPoint} | Talep: ${newQuantity} adet`;
          alerts.push(alertMsg);
          detailedAlerts.push(
            `- ${shop.name}: ${assignedCount}/${reorderPoint} stok. ${newQuantity} mühür talep edildi. (7 günlük tahmin: ${predictedDemand})`
          );

          logger.info(
            { shopId: shop.id, shopName: shop.name, assignedCount, reorderPoint },
            "seal_forecast_auto_request_created"
          );
        }
      } catch (shopErr) {
        logger.error({ err: shopErr, shopId: shop.id }, "seal_forecast_shop_error");
      }
    }

    // BUG-16: Send summary notification instead of triggering per shop
    if (autoRequests > 0) {
      const adminEmail = process.env.ADMIN_EMAIL?.trim();
      const summaryText = detailedAlerts.join("\n");

      if (adminEmail) {
        const emailSubject = `BagajPark [Admin]: ${autoRequests} Dükkan için Otomatik Mühür Talebi`;
        const emailBody = `Aşağıdaki dükkanlar için düşük mühür stoku nedeniyle otomatik talepler oluşturuldu:\n\n${summaryText}\n\nAdmin panelinden onaylayın: https://bagajpark.com/tr/admin/seals`;
        await notificationService.sendEmail(adminEmail, emailSubject, emailBody).catch(e => logger.error({ err: e }, "seal_forecast_email_summary_failed"));
      }

      for (const adminPhone of parseAdminGsmNumbers()) {
        const sms = `BagajPark: ${autoRequests} dükkan için mühür talebi açıldı. Detaylar email ile gönderildi.`;
        await notificationService.sendSms(adminPhone, sms).catch(e => logger.error({ err: e }, "seal_forecast_sms_summary_failed"));
      }
    }

    logger.info({ processed, alerts: alerts.length, autoRequests }, "seal_forecast_complete");

    return NextResponse.json({
      ok: true,
      processed,
      alerts,
      autoRequests,
    });
  } catch (err) {
    logger.error({ err }, "seal_forecast_failed");
    return NextResponse.json(
      { ok: false, error: err instanceof Error ? err.message : "unknown" },
      { status: 500 }
    );
  }
}

/**
 * Daily cron: mühür stok tahmini ve otomatik talep oluşturma.
 * Auth: Authorization: Bearer <CRON_SECRET>
 */
export async function GET(req: NextRequest) {
  return runSealForecast(req);
}

export async function POST(req: NextRequest) {
  return runSealForecast(req);
}
